/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Caixeiro;

/**
 *
 * @author Josinaldo Batista
 */
public class Form extends javax.swing.JFrame {
    
    private CaixeiroViajante cv;

    /**
     * Creates new form Form
     */
    public Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblProblema = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txbProblema = new javax.swing.JTextArea();
        lblCidades = new javax.swing.JLabel();
        txbCidades = new javax.swing.JTextField();
        lblArestas = new javax.swing.JLabel();
        txbArestas = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txbSolucao = new javax.swing.JTextArea();
        lblSolucao = new javax.swing.JLabel();
        cbAlgoritmos = new javax.swing.JComboBox();
        lblAlgoritmo = new javax.swing.JLabel();
        btnResolver = new javax.swing.JButton();
        btnLimparSolucao = new javax.swing.JButton();
        btnLimparPCV = new javax.swing.JButton();
        btnGerar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txbPossibilidades = new javax.swing.JTextArea();
        lblPossibilidades = new javax.swing.JLabel();
        painelGrafico = new Grafo();
        lblGrafo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Caixeiro viajante");
        setMaximumSize(new java.awt.Dimension(645, 370));
        setMinimumSize(new java.awt.Dimension(645, 370));
        setResizable(false);

        lblProblema.setText("Problema:");

        txbProblema.setColumns(20);
        txbProblema.setRows(5);
        jScrollPane1.setViewportView(txbProblema);

        lblCidades.setText("Cidades:");

        lblArestas.setText("Arestas:");

        txbSolucao.setColumns(20);
        txbSolucao.setRows(5);
        jScrollPane2.setViewportView(txbSolucao);

        lblSolucao.setText("Solução:");

        cbAlgoritmos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Força Bruta", "Aleatório", "Personalizado" }));

        lblAlgoritmo.setText("Algoritmo:");

        btnResolver.setText("Resolver");
        btnResolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResolverActionPerformed(evt);
            }
        });

        btnLimparSolucao.setText("Limpar");
        btnLimparSolucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparSolucaoActionPerformed(evt);
            }
        });

        btnLimparPCV.setText("Limpar");
        btnLimparPCV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparPCVActionPerformed(evt);
            }
        });

        btnGerar.setText("Gerar");
        btnGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarActionPerformed(evt);
            }
        });

        txbPossibilidades.setColumns(20);
        txbPossibilidades.setRows(5);
        jScrollPane3.setViewportView(txbPossibilidades);

        lblPossibilidades.setText("Possibilidades:");

        painelGrafico.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout painelGraficoLayout = new javax.swing.GroupLayout(painelGrafico);
        painelGrafico.setLayout(painelGraficoLayout);
        painelGraficoLayout.setHorizontalGroup(
            painelGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        painelGraficoLayout.setVerticalGroup(
            painelGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lblGrafo.setText("Gráfico");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblProblema)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLimparPCV)
                        .addGap(5, 5, 5)
                        .addComponent(btnGerar))
                    .addComponent(lblCidades)
                    .addComponent(lblArestas)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                    .addComponent(txbArestas)
                    .addComponent(txbCidades))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLimparSolucao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnResolver))
                    .addComponent(lblSolucao)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbAlgoritmos, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPossibilidades)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAlgoritmo))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblGrafo)
                        .addGap(0, 300, Short.MAX_VALUE))
                    .addComponent(painelGrafico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCidades)
                    .addComponent(lblAlgoritmo)
                    .addComponent(lblGrafo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txbCidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbAlgoritmos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblArestas)
                            .addComponent(lblPossibilidades))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblSolucao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txbArestas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblProblema)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnResolver)
                            .addComponent(btnLimparSolucao)
                            .addComponent(btnLimparPCV)
                            .addComponent(btnGerar)))
                    .addComponent(painelGrafico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Inicializa o problema do caxeiro viajante
     *
     * @param evt
     */
    private void btnGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarActionPerformed
        try {
            int cidades = Integer.parseInt(txbCidades.getText());
            int arestas = Integer.parseInt(txbArestas.getText());
            if (arestas >= cidades && arestas <= cidades * (cidades - 1)) {
                cv = new CaixeiroViajante(cidades, arestas);
                txbProblema.setText(cv.ExibirCaminhos());
                ((Grafo)painelGrafico).setCidades(cv.getCidades());
                painelGrafico.repaint();
            } else {
                txbProblema.setText("Impossível resolver o problema com esses valores.");
            }
        } catch (Exception e) {
            txbProblema.setText("Verifique se o campo cidades e arestas estão preechidos corretamente.");
        }
    }//GEN-LAST:event_btnGerarActionPerformed

    /**
     * Zera o problema do caxeiro viajante
     *
     * @param evt
     */
    private void btnLimparPCVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparPCVActionPerformed
        txbProblema.setText("");
        cv = null;
    }//GEN-LAST:event_btnLimparPCVActionPerformed

    /**
     * resolve o problema do caxeiro viajante
     *
     * @param evt
     */
    private void btnResolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResolverActionPerformed
        if (cv != null) {
            if (cbAlgoritmos.getSelectedItem().equals("Força Bruta")) {
                txbPossibilidades.setText(cv.ForcaBruta());
            } else if (cbAlgoritmos.getSelectedItem().equals("Aleatório")) {
                txbPossibilidades.setText(cv.Aleatorio());
            } else {
                txbPossibilidades.setText(cv.ResolucaoPersonalizada());
            }
            
            txbSolucao.setText(cv.ExibirMelhorCaminho());
        } else {
            txbSolucao.setText("Problema não inicializado");
        }
    }//GEN-LAST:event_btnResolverActionPerformed
    
    /**
     * Limpa o txbSolucao e o txbPossibilidades
     * @param evt 
     */
    private void btnLimparSolucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparSolucaoActionPerformed
        txbPossibilidades.setText("");
        txbSolucao.setText("");
    }//GEN-LAST:event_btnLimparSolucaoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGerar;
    private javax.swing.JButton btnLimparPCV;
    private javax.swing.JButton btnLimparSolucao;
    private javax.swing.JButton btnResolver;
    private javax.swing.JComboBox cbAlgoritmos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblAlgoritmo;
    private javax.swing.JLabel lblArestas;
    private javax.swing.JLabel lblCidades;
    private javax.swing.JLabel lblGrafo;
    private javax.swing.JLabel lblPossibilidades;
    private javax.swing.JLabel lblProblema;
    private javax.swing.JLabel lblSolucao;
    private javax.swing.JPanel painelGrafico;
    private javax.swing.JTextField txbArestas;
    private javax.swing.JTextField txbCidades;
    private javax.swing.JTextArea txbPossibilidades;
    private javax.swing.JTextArea txbProblema;
    private javax.swing.JTextArea txbSolucao;
    // End of variables declaration//GEN-END:variables
}
